// Execution evidence is generated by the orchestrator, never by model claims.
export function isGameSaveRequest(text) {
  return /\b(?:infinite ammo|game save|edit(?: the)? save|sinking city|tsc2)\b|ذخيرة(?:\s+لا نهائية)?|حفظ اللعبة/i.test(
    text,
  );
}

export function preparePlan(state, text) {
  if (state.status === "cancelled" || state.plan.length) return;
  if (isGameSaveRequest(text)) {
    state.plan = ["inspect", "edit"].map((kind) => ({
      kind,
      status: "pending",
      evidence: [],
    }));
    return;
  }
  if (
    !/\b(?:fix|patch|implement|build|debug|run.*tests|coding)\b|أصلح|نفذ|اختبر/i.test(
      text,
    )
  )
    return;
  const testOnly =
    /\brun\b.*\btests\b/i.test(text) &&
    !/\b(?:fix|patch|implement|build|debug)\b/i.test(text);
  state.plan = (
    testOnly ? ["inspect", "test"] : ["inspect", "edit", "test", "review"]
  ).map((kind) => ({ kind, status: "pending", evidence: [] }));
}

const stage = (name) =>
  ({
    project_map: "inspect",
    read_file: "inspect",
    search_code: "inspect",
    list_files: "inspect",
    game_save_inspect: "inspect",
    write_file: "edit",
    apply_patch: "edit",
    game_save_prepare: "edit",
    game_save_apply: "edit",
    game_save_restore: "edit",
    run_tests: "test",
    run_check: "check",
    git_diff: "review",
    git_status: "review",
  })[name];

export function recordExecution(
  state,
  name,
  { success, code, filtered = false, blocked = false },
) {
  const evidence = {
    id: `${state.turn}:${(state.executionSequence = (state.executionSequence ?? 0) + 1)}`,
    turn: state.turn,
    name,
    success,
    ...(typeof code === "number" ? { code } : {}),
    filtered,
    blocked,
  };
  state.toolsUsed = [...state.toolsUsed, evidence].slice(-64);
  const kind = stage(name);
  if (!success) {
    state.failedStrategies = [
      ...state.failedStrategies,
      { ...evidence, resolved: false },
    ].slice(-24);
    const step = state.plan.find((s) => s.kind === kind);
    if (step) step.status = "blocked";
    state.completedSteps = state.plan
      .filter((s) => s.status === "completed")
      .map((s) => ({ kind: s.kind, evidence: s.evidence }));
    return;
  }
  // A successful same-category check supersedes a failed check, but a successful
  // read must not erase an unrelated edit/command failure.
  if (kind === "test" || kind === "check") {
    for (const failure of state.failedStrategies)
      if (failure.name === name) failure.resolved = true;
  }
  if (kind === "edit" || name === "terminal") {
    for (const step of state.plan)
      if (["test", "review"].includes(step.kind)) {
        step.status = "pending";
        step.evidence = [];
      }
  }
  const step = state.plan.find((s) => s.kind === kind);
  // Only zero-exit test runs count as successful verification.
  if (step && (kind !== "test" || (code === 0 && !filtered))) {
    step.status = "completed";
    step.evidence = [...step.evidence, evidence.id].slice(-8);
  }
  state.completedSteps = state.plan
    .filter((s) => s.status === "completed")
    .map((s) => ({ kind: s.kind, evidence: s.evidence }));
}

export function evaluateFinal(state, content) {
  const prose = content
    .replace(/```[\s\S]*?```/g, "")
    .split(/[.!?\n]+/)
    .filter(
      (sentence) =>
        !/^\s*>/.test(sentence) &&
        !/\b(?:not|never|cannot|can[’']t|couldn[’']t|haven[’']t|unverified|whether|if|when|until)\b|لم|لا أستطيع/i.test(
          sentence,
        ),
    )
    .join(". ");
  const claimsGameplay =
    /\b(?:confirmed working in gameplay|gameplay (?:is )?(?:confirmed|verified)|verified in[- ]game|works in gameplay|the game recognized)\b|تأكدت من اللعب|ثبت في اللعب/i.test(
      prose,
    );
  if (claimsGameplay) {
    return {
      ok: false,
      kind: "gameplay",
      reason:
        "A gameplay-confirmed claim is not allowed from disk verification alone. Say the save was modified and verified on disk, and that gameplay is still unconfirmed until the user tests it.",
    };
  }
  const claimsTests =
    /\b(?:all\s+)?tests?\s+(?:have\s+)?pass(?:ed)?\b|\btest suite\s+(?:is\s+)?(?:green|pass(?:ed)?)\b|نجحت (?:جميع )?الاختبارات/i.test(
      prose,
    );
  if (!claimsTests) return { ok: true };
  const executions = state.toolsUsed;
  const lastEdit = executions.findLastIndex(
    (e) => stage(e.name) === "edit" || e.name === "terminal",
  );
  const lastTest = executions.findLastIndex((e) => e.name === "run_tests");
  const evidence = executions[lastTest];
  if (
    lastTest > lastEdit &&
    evidence?.success &&
    evidence.code === 0 &&
    !evidence.filtered
  )
    return { ok: true };
  return {
    ok: false,
    kind: "tests",
    reason:
      "A tests-passed claim needs a successful run_tests exit code 0 after the latest edit. Run the tests, or state that the result is unverified.",
  };
}
